# Numpy Tutorial
## from http://cs231n.github.io/python-numpy-tutorial/

## Python data types

In [1]:
# first check python version
import sys
print('%s.%s.%s' % sys.version_info[:3])
# 3.5.2

3.5.2


In [2]:
# data types
x = 3
print( type(x)) # Prints "<type 'int'>"
print(x) # 3
print( x + 1) # 4
print( x - 1) # 2
print( x * 2) # 6
print( x ** 2) # exponentiation. prints 9
x += 1 # increments x
print( x) # prints 4
x *= 2
print( x) # prints 8
y = 2.5
print( type(y)) # prints <type 'float'>
print( y, y + 1, y * 2, y ** 2) # prints "2.5 3.5 5.0 6.25"

# python does not have unary increment and decrement operators

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [3]:
# strings
hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw = hello + ' ' + world
print(hw)
hw12 = '%s %s %d' % (hello, world, 12) # sprintf style string formatting
print(hw12)

hello
5
hello world
hello world 12


In [4]:
# ... todo: finish python data types

# Numpy Data Types


In [5]:
# arrays
import numpy as np
a = np.array([1, 2, 3]) # create a rank 1 array
print(type(a)) # prints "<type 'numpy.ndarray'>"
print(a.shape) # prints "(3,)"
print(a[0], a[1], a[2]) # prints "1 2 3"
a[0] = 5 # change an element in the array
print(a) # prints "[5, 2, 3]"

# now create a rank 2 array
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b.shape) # prints (2, 3)
print(b[0, 0], b[0, 1], b[1, 0]) # prints 1 2 4

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [6]:
# numpy supports many ways of creating arrays

a = np.zeros((2,2))  # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                     #          [ 0.  0.]]"
    
b = np.ones((1,2))   # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7) # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                      #          [ 7.  7.]]"

d = np.eye(2)        # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                     #          [ 0.  1.]]"
    
e = np.random.random((2,2)) # Create an array filled with random values
print(e)                    # Might print "[[ 0.91940167  0.08143941]
                            #               [ 0.68744134  0.87236687]]"

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.17668428  0.50431159]
 [ 0.27161508  0.40002048]]


/opt/conda/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [7]:


# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]

# this is called "slice indexing"
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [9]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
# (variables are references to a single array object)

print(a)
b[0,0] = 77
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#